services:
  nodeapp:
    image: node:22
    working_dir: /app
    volumes:
      - .:/app
    command: node index.js
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  postgres:
    image: postgres:17-bullseye
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      # - pgdata: /var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# volumes:
#   pgdata: /var/lib/postgresql/data