services:
  nodeapp:
      image: node:22
      env_file: 
        - ../.env.test.local
      working_dir: /app
      volumes:
        - ../.:/app
      command: bash -c "npm i && npm run test:e2e"
      ports:
        - "3000:3000"
      depends_on:
        - postgres