services:
  nodeapp:
      image: node:22
      env_file: 
        - ../env
      working_dir: /app
      volumes:
        - ../.:/app
      command: bash -c "npm i && npm run start:prod"
      ports:
        - "3000:3000"
      depends_on:
        - postgres